[header]
font-weight = 700
max-width = 700px
margin-left = auto
margin-right = auto
background = {{mantle}}
padding = 5px 5px 0

[header-fake-button]
color = {{crust}}
background = {{mauve}}
border = 4px solid {{mauve}}
border-right = 4px outset {{mauve}}
height = 30px
font-family = monospace

[header-rest]
background = transparent

[profile-main]
border = 4px outset {{mauve}}
background-image = url("https://cdn.derg.space/assets/af/memphis-mini-dark.png")
background-attachment = fixed
min-height = 200px
max-width = 700px
margin-left = auto
margin-right = auto

[profile-content]
background-color = rgba(49, 50, 68, 0.2)

[profile-bottom-wave]
display = block
width = 100%
height = 600px
margin-top = -600px
background-image = url(https://cdn.derg.space/assets/af/wave.png)
background-repeat = repeat-x
background-position = bottom
background-size = 100%

[profile-dead-dog]
float = right
margin-bottom = -20px
margin-top = -30px
height = 150px
width = 150px

[trait-header]
line-height = 1.05
font-size = 1.17em
font-weight = 700

; oc card
[oc-list-root]

[oc-card]
border = 3px dotted #fab387
border-radius = 0.4rem
padding = 0.5em

[oc-bouncer]
height = 0
line-height = 0

[oc-bouncer-known]
display = inline-block
margin-top = -95px

[oc-bouncer-vera]
display = inline-block
margin-top = -82px
height = 90px
; end oc card

[breathing-mario]
font-size = 2em
line-height = 1

[footer]
width = 100%
border = 2px inset {{mauve}}
align-items = center

[footer-vistor-counter]
border = 2px inset {{base}}

[footer-source-align]
max-width = 700px
margin-left = auto
margin-right = auto
color = {{crust}}

[footer-source-url-i]
font-size = 1.5em
padding-top = 0.2em

[interest-entry]
font-size = 1.08em
margin-top = 0.1em
line-height = 1.12

;tailwind ish stuff
[nomargin]
margin = 0

[bg-mauve]
background = {{mauve}}